# Generated by Django 4.2.5 on 2023-10-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_alter_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
                ('center_addr', models.CharField(max_length=255)),
                ('center_phone', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register')),
            ],
            options={
                'db_table': 'service_center',
            },
        ),
        migrations.CreateModel(
            name='service_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='media')),
                ('service_Package_name', models.CharField(max_length=350, null=True)),
                ('car_name', models.CharField(choices=[('Bolero', 'Bolero'), ('BR-V', 'BR-V'), ('scorpio', 'scorpio'), ('XUV500', 'XUV500'), ('Aspire', 'Aspire')], max_length=255)),
                ('service_category', models.CharField(choices=[('Periodic services', 'Periodic services'), ('AC Service', 'AC Service'), ('Denting and Penting', 'Denting and Penting'), ('Car Batteries', 'Car Batteries'), ('Tayers and Wheel Care', 'Tayers and Wheel Care'), ('Car Spa', 'Car Spa')], max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=350)),
                ('s_center_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.s_center')),
                ('userobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register')),
            ],
            options={
                'db_table': 'service_Detail',
            },
        ),
    ]
