# Generated by Django 4.2.5 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=255)),
                ('appintment_date', models.DateField()),
                ('car_name', models.CharField(max_length=255)),
                ('car_no', models.CharField(max_length=255)),
                ('customer_fname', models.CharField(max_length=255)),
                ('customer_lname', models.CharField(max_length=255)),
                ('customer_contact', models.BigIntegerField()),
                ('service_category', models.CharField(max_length=255)),
                ('service_package', models.CharField(max_length=255)),
                ('package_amount', models.FloatField()),
                ('additional_work', models.CharField(default='', max_length=255)),
                ('additional_cahrge', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('delivery_date', models.DateField(default='')),
                ('payment_status', models.CharField(default='Pending', max_length=255)),
                ('status', models.CharField(default='Active', max_length=255)),
            ],
            options={
                'db_table': 'service_record_detail',
            },
        ),
        migrations.CreateModel(
            name='service_record_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=255)),
                ('appintment_date', models.DateField()),
                ('car_name', models.CharField(max_length=255)),
                ('car_no', models.CharField(max_length=255)),
                ('customer_fname', models.CharField(max_length=255)),
                ('customer_lname', models.CharField(max_length=255)),
                ('customer_contact', models.BigIntegerField()),
                ('service_category', models.CharField(max_length=255)),
                ('service_package', models.CharField(max_length=255)),
                ('package_amount', models.FloatField()),
                ('additional_work', models.CharField(default='', max_length=255)),
                ('additional_cahrge', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('delivery_date', models.DateField(null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=255)),
                ('status', models.CharField(default='Active', max_length=255)),
            ],
            options={
                'db_table': 'service_center_record_detail',
            },
        ),
    ]
