# Generated by Django 4.2.5 on 2023-11-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_service_record_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_record',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service_record_detail',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
