# Generated by Django 4.2.5 on 2023-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_service_record_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_record',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
