# Generated by Django 4.2.5 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_service_record_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_record',
            name='payment_mode',
            field=models.CharField(default='online', max_length=255),
        ),
    ]
