# Generated by Django 4.2.5 on 2023-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_service_record_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(max_length=300)),
                ('payment_status', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=300)),
                ('appointment_no', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'payment_detail',
            },
        ),
    ]
