# Generated by Django 4.2.5 on 2023-10-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='user_ecord',
        ),
    ]
