# Generated by Django 4.2.5 on 2023-11-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_alter_register_table'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.FloatField()),
                ('customerobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register')),
                ('serviceobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.service_detail')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
