# Generated by Django 4.2.5 on 2023-11-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.TextField(max_length=255)),
                ('customer_lname', models.TextField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_contact', models.TextField(max_length=255)),
                ('service_center_name', models.TextField(max_length=255)),
                ('service_center_contact', models.TextField(max_length=255)),
                ('service_package', models.TextField(max_length=255)),
                ('service_category', models.TextField(max_length=255)),
                ('Totalamount', models.FloatField()),
                ('appoinment_Date', models.DateField()),
                ('service_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
