# Generated by Django 4.2.5 on 2023-11-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.service_detail'),
        ),
    ]
