# Generated by Django 4.2.5 on 2023-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_order_service_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_no',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Not Approved', max_length=255),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Appointment',
        ),
    ]
