# Generated by Django 4.2.5 on 2023-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_appointment_no_order_status_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_center_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
