# Generated by Django 4.2.5 on 2023-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_service_center_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='car_no',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
